---
title: матриця push та pop
hero_image: images/banner.png
description: матриця push та pop
version: 4
listed: false
copyedit: false
last_tested: "2021-09-28"
steps:
  - 
    title: Матриця push та pop
