---
title: matriz "push" e "pop"
hero_image: images/banner.png
description: matriz "push" e "pop"
version: 4
listed: false
copyedit: false
last_tested: "2021-09-28"
steps:
  - 
    title: Matriz "push" e "pop"
